apiVersion: extensions/v1beta1                #api版本
kind: Ingress                                #清单类型
metadata:                                    #元数据
  name: ingress-default-backend                #ingress名称
  namespace: ingress-nginx                    #所属命名空间
  annotations:                                #注解信息
    kubernetes.io/ingress.class: "nginx"
spec:                                        #规格
  rules:                                    #定义后端转发规则
  - host: default.backend.com                #通过域名进行转发
    http:
      paths:
        - path:                                #配置访问路径
          backend:                            #配置后端服务
            serviceName: default-http-backend
            servicePort: 80






