10:52:05.366528 <0.5926.0> lager_transform:parse_transform([{attribute,1,file,{"lib/demo_lager-0.1.0/src/demo_lager_server.erl",1}},
 {attribute,9,module,demo_lager_server},
 {attribute,10,author,"zhaoweiguo"},
 {attribute,12,behaviour,gen_server},
 {attribute,15,export,[{start_link,0},{stop,0}]},
 {attribute,18,export,
     [{init,1},
      {handle_call,3},
      {handle_cast,2},
      {handle_info,2},
      {terminate,2},
      {code_change,3}]},
 {attribute,26,record,{state,[]}},
 {function,29,start_link,0,
     [{clause,29,[],[],
          [{call,30,
               {remote,30,{atom,30,gen_server},{atom,30,start_link}},
               [{atom,30,demo_lager_server},{nil,30},{nil,30}]}]}]},
 {function,32,stop,0,
     [{clause,32,[],[],
          [{call,32,
               {remote,32,{atom,32,gen_server},{atom,32,call}},
               [{call,32,{atom,32,self},[]},{atom,32,stop}]}]}]},
 {function,36,init,1,
     [{clause,36,
          [{nil,36}],
          [],
          [{call,37,
               {remote,37,{atom,37,lager},{atom,37,info}},
               [{string,37,"client process start"}]},
           {tuple,38,
               [{atom,38,ok},{record,38,state,[]},{integer,38,1000}]}]}]},
 {function,41,handle_call,3,
     [{clause,41,
          [{var,41,'_Request'},{var,41,'_From'},{var,41,'State'}],
          [],
          [{call,42,
               {remote,42,{atom,42,lager},{atom,42,info}},
               [{string,42,"handle_call _Request = ~p"},
                {cons,42,{var,42,'_Request'},{nil,42}}]},
           {tuple,43,[{atom,43,reply},{atom,43,ok},{var,43,'State'}]}]}]},
 {function,45,handle_cast,2,
     [{clause,45,
          [{var,45,'_Request'},{var,45,'State'}],
          [],
          [{call,46,
               {remote,46,{atom,46,lager},{atom,46,info}},
               [{string,46,"handle_cast _Request"},
                {cons,46,{var,46,'_Request'},{nil,46}}]},
           {tuple,47,[{atom,47,noreply},{var,47,'State'}]}]}]},
 {function,49,handle_info,2,
     [{clause,49,
          [{var,49,'_Info'},{var,49,'State'}],
          [],
          [{match,50,
               {var,50,'F'},
               {'fun',50,
                   {clauses,
                       [{clause,50,
                            [{var,50,'_'}],
                            [],
                            [{call,51,
                                 {remote,51,{atom,51,lager},{atom,51,info}},
                                 [{string,51,
                                      "=======>> handle_info _Info=======>> handle_info _Info = ~p"},
                                  {cons,51,{var,51,'_Info'},{nil,51}}]},
                             {atom,59,ok}]}]}}},
           {call,62,
               {remote,62,{atom,62,lists},{atom,62,foreach}},
               [{var,62,'F'},
                {call,62,
                    {remote,62,{atom,62,lists},{atom,62,seq}},
                    [{integer,62,1},{integer,62,100}]}]},
           {tuple,63,
               [{atom,63,noreply},{var,63,'State'},{integer,63,100}]}]}]},
 {function,66,terminate,2,
     [{clause,66,
          [{var,66,'_Reason'},{var,66,'_State'}],
          [],
          [{call,67,
               {remote,67,{atom,67,lager},{atom,67,info}},
               [{string,67,"terminate"}]},
           {atom,68,ok}]}]},
 {function,70,code_change,3,
     [{clause,70,
          [{var,70,'_OldVsn'},{var,70,'State'},{var,70,'_Extra'}],
          [],
          [{tuple,71,[{atom,71,ok},{var,71,'State'}]}]}]},
 {eof,78}], [report_errors,report_warnings,{parse_transform,lager_transform}])





