apiVersion: batch/v1
kind: Job
metadata:
  name: busybox
  labels:
      name: busybox
spec:
  template:
    metadata:
      name: busybox
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: registry.cn-beijing.aliyuncs.com/octopus-test/analysis-once:v1
        imagePullPolicy: IfNotPresent
        command: ["/analysis-once", "--start=20190101", "--end=20190819"]
      restartPolicy: Never

      # restartPolicy: Never  #如果使用参数Never，容器启动后未成功就会一直创建新的容器
      # restartPolicy: OnFailure  #如果使用参数OnFailure，容器启动后未成功不会在创建新的容器，他会一直重启

      # imagePullPolicy: IfNotPresent
      # imagePullPolicy: Always


