apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: 'yes'
  creationTimestamp: '2019-08-21T06:43:14Z'
  finalizers:
    - kubernetes.io/pv-protection
  labels:
    alicloud-pvname: d-2zeetkf4u46w1vj3r2jf
    failure-domain.beta.kubernetes.io/region: cn-beijing
    failure-domain.beta.kubernetes.io/zone: cn-beijing-h
  name: d-2zeetkf4u46w1vj3r2jf
  resourceVersion: '17424589'
  selfLink: /api/v1/persistentvolumes/d-2zeetkf4u46w1vj3r2jf
  uid: f36131b3-c3de-11e9-a845-0ae9559f92f8
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi  #  定义PV的大小
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: disk-ssd-ruler-eureka0
    namespace: default
    resourceVersion: '17424586'
    uid: 279661cb-c3df-11e9-802c-6a93fcf53165
  flexVolume:
    driver: alicloud/disk
    fsType: ext4
    options:
      volumeId: d-2zeetkf4u46w1vj3r2jf
  persistentVolumeReclaimPolicy: Delete   # 声明被释放后，pv将会被清理、删除
  storageClassName: disk
status:
  phase: Bound






