apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: goanalysis
  labels:
    app: goanalysis
spec:
  schedule: "5 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: goanalysis
          labels:
            app: goanalysis
        spec:
          containers:
            - name: goanalysis
              image: registry.cn-beijing.aliyuncs.com/octopus-test/goanalysis:v5
              imagePullPolicy: IfNotPresent
              command: ["/goanalysis"]
              resources:
                requests:
                  memory: "128Mi"
                limits:
                  memory: "256Mi"
          restartPolicy: OnFailure


