apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"prometheus.yml":"global:\n  scrape_interval:
      30s\n  scrape_timeout: 30s\nscrape_configs:\n- job_name: 'prometheus'\n 
      static_configs:\n    - targets: ['localhost:9090']\n- job_name:
      'kubernetes-nodes'\n  scheme: https\n  tls_config:\n    ca_file:
      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt\n   
      insecure_skip_verify: true\n  bearer_token_file:
      /var/run/secrets/kubernetes.io/serviceaccount/token\n 
      kubernetes_sd_configs:\n  - api_servers:\n    -
      'https://kubernetes.default.svc'\n    in_cluster: true\n    role: node\n 
      relabel_configs:\n  - action: labelmap\n    regex:
      __meta_kubernetes_node_label_(.+)\n  - target_label: __address__\n   
      replacement: kubernetes.default.svc:443\n  - source_labels:
      [__meta_kubernetes_node_name]\n    regex: (.+)\n    target_label:
      __metrics_path__\n    replacement:
      /api/v1/nodes/${1}/proxy/metrics\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"prometheus-config","namespace":"monitoring"}}
  creationTimestamp: '2020-05-27T10:28:12Z'
  name: prometheus-config
  namespace: monitoring
  resourceVersion: '4571397651'
  selfLink: /api/v1/namespaces/monitoring/configmaps/prometheus-config
  uid: c4924c01-a004-11ea-a65f-a625c556031c
