apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: deploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers: []
      volumes:
        - configMap:
            name: prometheus-config
          name: app
