#!/bin/sh
# chkconfig:   2345 90 10
# description:  Redis is a persistent key-value database
EXEC="/usr/local/redis-2.6.14/src/redis-server"
CLIEXEC="/usr/local/redis-2.6.14/src/redis-cli"
PIDFILE="/var/redis/redis.pid"
CONF="/usr/local/redis-2.6.14/redis.conf"
PORT="6379"

case "$1" in
    start)
        if [ -f $$PIDFILE ]
        then
                echo "$PIDFILE exists, process is already running or crashed."
        else
                echo "Starting Redis server..."
                $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
                echo "$PIDFILE does not exist, process is not running."
        else
                PID=$(cat $PIDFILE)
                echo "Stopping ..."
                $CLIEXEC -p $PORT shutdown
                while [ -x /proc/${PID} ]
                do
                    echo "Waiting for Redis to shutdown ..."
                    sleep 1
                done
                echo "Redis stopped."
        fi
        ;;
    restart)
        $0 stop && $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac


